### ISSUE TITLE
Split Bool into And and Or types

### ISSUE THREAD

**Issue by broomburgo** [broomburgo/Abstract#1]
Like it was done with numeric types, for which `Add` and `Multiply` were defined with a specific binary operation and proper `empty` distinguished element, it should probably be the same for `Bool`: the current implementation is the one for `And`.

**Comment by mbrandonw** [comment]
In addition to this, you could add a new algebraic type called [semiring](https://en.wikipedia.org/wiki/Semiring), which allows an object to have two operations on it that play nicely with each other (i.e. one distributes over the other).

`Bool` has a nice semiring structure and so does `Predicate<A>`, which allows you to combine predicates in more ways.

I've also drafted an intro to this stuff for my blog [here](https://github.com/mbrandonw/mbrandonw.github.io/blob/master/_drafts/semirings-and-predicates.md). There might be a lot of typos in that, so take it with a grain of salt!

Also, nice job on this lib! It looks great!

**Comment by broomburgo** [comment]
Whoa I didn't notice that you added the article "The Algebra of Predicates and Sorting Functions" to fewbutripe, great!

I was actually searching for a practical application of Semiring before defining it in the library, and it looks like Bool and Predicate is and excellent idea, thanks for the suggestion.

I just added to the PR a more precise definition of Predicate for And and Or, and I'm going to work at the Bool Semiring after the PR gets merged.
