### ISSUE TITLE
Dependency on Operadics

### ISSUE THREAD

**Issue by broomburgo** [broomburgo/Abstract#23]
I'm starting to use this library in some projects, including other libraries, but the dependency on `Operadics` as it's set up is not very convenient: the need to build `Operadics` after `carthage checkout` is present (of course) also if `Abstract` is a dependency of another library, which means that after a `carthage update` that includes that library, I still need to manually build `Operadics` for the nested dependency, rendering the Carthage process really cumbersome. Before filing and issue on `Operadics` asking for Carthage compatibility I was wondering if there's a way to make it work automatically with the current setup: I thought about adding a build phase but doing it so will repeat over and over again the checkout/build step for `Operadics` that's really only needed once. Any thoughts?

**Comment by bkase** [comment]
Hmm yeah good point. I think this should probably be fixed over in Operadics honestly. Redoing checkout and build every time seems pretty wasteful.
