### ISSUE TITLE
Should "Magma" inherit from "Equatable"?

### ISSUE THREAD

**Issue by broomburgo** [broomburgo/Abstract#25]
In using Abstract in my daily work I found that basically every concrete type that I make implementing some algebraic protocol in the end must always be "Equatable" to be really useful.

Should we impose this in general and make Magma inherit from Equatable? I find myself already needing to wrap the standard generic types like Optional and Array into wrapper types with additional constraints, something that is going to change once [SE-0143](https://github.com/apple/swift-evolution/blob/master/proposals/0143-conditional-conformances.md) is implemented, for making them conform to equatable: that's annoying (and Sourcery helps a lot), but still it's seem definitely required in many real-world applications.

What do you think?

**Comment by bkase** [comment]
@broomburgo There are a few useful magmas that aren't equatable though right? Like EndoFunction and FunctionM (and any compound type with a function inside of it)

**Comment by bkase** [comment]
If we could somehow unify Equatable and EquatableInContext that may cover most things -- but imagine about higher-order function structures that had algebraic structure. I bet there are interesting things there.

**Comment by broomburgo** [comment]
Yep you're right, no luck there :D

I'm closing the issue.
